spring:
  application:
    name: ep-auth-server
  main:
    allow-circular-references: true
  profiles:
    active: local
  cloud:
    config:
      uri: http://localhost:8888
      profile: local

eureka:
  client:
    service:
     defaultZone: http://localhost:8761/eureka/

server:
  port: 6061
